import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const html = readFileSync(new URL("../1984.html", import.meta.url), "utf8");
const client = readFileSync(new URL("./client.mjs", import.meta.url), "utf8");

function sliceFn(source, name) {
  const start = source.indexOf("function " + name + "(");
  assert.notEqual(start, -1, name);
  const next = source.indexOf("\nfunction ", start + 1);
  return source.slice(start, next === -1 ? source.length : next);
}

test("the buy ask closes without starting a purchase", () => {
  assert.match(html, /id="ask-close">Close<\/button>/);
  assert.match(html, /id="ask-ok">OK<\/button>/);
  assert.match(html, /id="ask-no">Not now<\/button>/);
  assert.match(html, /id="pay-slip-close">Close<\/button>/);
  assert.match(html, /id="pay-slip-again">New purchase<\/button>/);
  const ask = sliceFn(client, "askOk");
  assert.match(ask, /close\.addEventListener\("click", onNo\)/);
  assert.match(ask, /finish\(false\)/);
  assert.doesNotMatch(ask, /newPurchase|openMode/);
});

test("the landing gate takes a funded test address", () => {
  const css = readFileSync(new URL("../1984.css", import.meta.url), "utf8");
  const faucet = readFileSync(new URL("../faucet.html", import.meta.url), "utf8");
  const rails = readFileSync(new URL("../rails.html", import.meta.url), "utf8");
  assert.match(html, /id="gate-guest">Use a funded test address<\/button>/);
  assert.doesNotMatch(html, /id="pay-toggle"/);
  assert.doesNotMatch(html, />Who pays</);
  assert.doesNotMatch(html, /id="mini"/);
  assert.match(html, /This money is tKAS\. tKAS is Testnet-10 KAS/);
  assert.match(html, /A funded wallet is prefunded with tKAS\. Spend it at will\. There is no risk\. tKAS is worthless\./);
  assert.match(html, /Testnet 10 · LUMBRIDGE/);
  assert.match(client, /1984\. LUMBRIDGE\. Testnet 10/);
  assert.match(rails, /The town on the page is LUMBRIDGE/);
  assert.match(rails, /A later quote does not reprice the lock/);
  assert.match(rails, /The tKAS already locked on that tag can still be redeemed/);
  assert.match(client, /Redeem returns the tKAS that was locked/);
  assert.doesNotMatch(client, /the lock no longer covers the tagged amount/);
  assert.doesNotMatch(html, /Ashfields/);
  assert.doesNotMatch(client, /Ashfields/);
  assert.doesNotMatch(rails, /Ashfields/);
  const gateHtml = html.slice(html.indexOf('id="gate"'));
  assert.doesNotMatch(gateHtml, /benchmark/);
  assert.doesNotMatch(gateHtml, /Wallet sign-in comes later/);
  assert.match(html, /With tKAS you can go to the bank and swap\./);
  assert.doesNotMatch(html, /id="gate-kasware"/);
  assert.doesNotMatch(html, /id="gate-kastle"/);
  assert.match(html, /The same browser gets the same funded wallet/);
  assert.match(html, /cannot tell it is the same browser/);
  assert.match(html, /1984\/client\.mjs\?v=138/);
  assert.match(client, /Use a funded test address/);
  assert.match(client, /With tKAS you can go to the bank/);
  assert.doesNotMatch(sliceFn(client, "paintChrome"), /id="use-kasware"/);
  assert.match(rails, /the funded list/);
  assert.match(rails, /funded-list\.json/);
  const phoneAt = css.indexOf("@media (max-width: 980px)");
  assert.ok(phoneAt > 0);
  const phone = css.slice(phoneAt);
  assert.match(html, /class="phone-fit"/);
  assert.match(html, /class="desk-note">Better on a desktop, a PC, or a laptop\./);
  assert.match(css.slice(0, phoneAt), /\.desk-note \{ display: none; \}/);
  assert.match(phone, /\.phone-fit \{[\s\S]*width: 100%;[\s\S]*height: 100%;[\s\S]*transform: none/);
  assert.doesNotMatch(phone, /width: 1280px/);
  assert.doesNotMatch(phone, /scale\(min\(/);
  assert.match(phone, /\.desk-note \{[\s\S]*display: block/);
  assert.match(phone, /body\.page-1984:has\(#gate:not\(\[hidden\]\)\) \.desk-note \{ display: none; \}/);
  assert.match(phone, /body\.page-1984 \.top nav \{[\s\S]*display: none/);
  assert.match(phone, /\.phone-fit \.kw-launch/);
  assert.match(phone, /\.phone-fit \.kw-hint \{ display: none; \}/);
  assert.doesNotMatch(phone, /\.hint-phone/);
  assert.match(phone, /\.phone-fit \.kw-step \{ display: inline-block; \}/);
  assert.match(phone, /\.phone-fit \.show-card \{[^}]*width: auto;[^}]*max-height: 62%/);
  assert.match(phone, /\.phone-fit \.kw-panel \{[^}]*width: auto;[^}]*max-height: 68%/);
  assert.match(phone, /\.phone-fit \.kw-panel\.swap-pop,\s*\.phone-fit \.kw-panel\.stall-pop \{[^}]*width: auto;[^}]*max-height: 78%;[^}]*transform: none/);
  assert.match(phone, /\.phone-fit \.kw-you \{[^}]*width: auto;[^}]*max-height: 62%/);
  assert.match(phone, /\.phone-fit \.kw-chat \{[^}]*width: auto;/);
  assert.match(phone, /\.phone-fit \.flight-card,\s*\.phone-fit \.flight-card\.ended \{[^}]*width: auto;[^}]*max-height: 52%/);
  assert.match(phone, /\.phone-fit #flight-line \{ font-size: 0\.82rem;/);
  assert.match(phone, /max-height: 560px\) \{[\s\S]*\.phone-fit #flight-line \{ font-size: 0\.68rem;/);
  assert.match(html, /id="flight-dest" hidden>Choose destination</);
  assert.match(html, /id="flight-end-pop"/);
  const endAt = html.indexOf('id="flight-end"');
  const offerAt = html.indexOf('id="flight-offer"');
  assert.ok(endAt > 0 && offerAt > endAt);
  assert.doesNotMatch(html.slice(offerAt, html.indexOf('id="flight-dest"')), /flight-end/);
  assert.match(css, /\.flight-end-pop \{[\s\S]*left: 12px;[\s\S]*bottom: 12px;/);
  assert.match(phone, /\.phone-fit \.flight-planets \{[\s\S]*overflow-y: auto;/);
  assert.match(phone, /\.phone-fit \.flight-end-pop \{[\s\S]*left: 8px;[\s\S]*bottom: 8px;/);
  assert.match(client, /function jokeForScreen/);
  assert.match(client, /old roadster/);
  assert.match(sliceFn(client, "syncFlightFilms"), /stopCommsSound\(\)/);
  assert.doesNotMatch(sliceFn(client, "syncFlightFilms"), /currentTime = 0\.49/);
  assert.match(sliceFn(client, "syncFlightFilms"), /HOT_STAGE_MS/);
  assert.match(phone, /\.phone-fit \.kw-side \{[^}]*width: 4\.4rem/);
  assert.doesNotMatch(phone, /\.kw \.kw-launch/);
  assert.doesNotMatch(phone, /p\.only-phone \{ display: block; \}/);
  assert.doesNotMatch(css.slice(0, phoneAt), /\.kw-wallets, \.wallet-pc \{ display: none; \}/);
  const town = html.match(/window\.TOWN_API = "([^"]+)"/);
  const tunnel = client.match(/const TUNNEL = "([^"]+)"/);
  const faucetApi = faucet.match(/window\.FAUCET_API = "([^"]+)"/);
  assert.ok(town && tunnel && faucetApi);
  assert.equal(town[1], faucetApi[1]);
  assert.equal(tunnel[1], faucetApi[1]);
  assert.match(client, /Bypass-Tunnel-Reminder/);
  assert.doesNotMatch(html, /Same kaspatest address, same history/);
  assert.doesNotMatch(html, /id="gate-addr"/);
  assert.doesNotMatch(html, /Open this address/);
  assert.match(client, /Same funded wallet\. This browser already had this address/);
  assert.match(client, /cannot tell this browser from a new one/);
  assert.doesNotMatch(html, /Come back later and that history is gone/);
  const guest = sliceFn(client, "startGuest");
  assert.match(guest, /hideGate\(\)/);
  assert.match(client, /function openFundedTest\(/);
  assert.match(client, /getElementById\("gate-guest"\)/);
});

test("the cinema snacks close to a small tab", () => {
  const css = readFileSync(new URL("../1984.css", import.meta.url), "utf8");
  assert.match(html, /id="show-snacks-close"[^>]*>Close snacks<\/button>/);
  assert.match(html, /id="show-snacks-tab"[^>]*>Snacks<\/button>/);
  assert.doesNotMatch(html, /id="show-snacks-tab"[^>]*data-pay/);
  assert.doesNotMatch(html, /id="show-snacks-close"[^>]*data-snack/);
  assert.doesNotMatch(html, /id="show-snacks-close"[^>]*data-pay/);
  const mark = sliceFn(client, "markShow");
  assert.match(mark, /snacksOpen\(\)/);
  assert.match(mark, /show-snacks-tab/);
  assert.match(mark, /show-snacks-close/);
  assert.match(mark, /show-snacks-box/);
  assert.match(sliceFn(client, "phoneLayout"), /max-width: 980px/);
  assert.match(sliceFn(client, "snacksOpen"), /phoneLayout\(\)/);
  const bind = sliceFn(client, "bindReel");
  const closeAt = bind.indexOf("#show-snacks-close");
  const tabAt = bind.indexOf("#show-snacks-tab");
  const snackAt = bind.indexOf("const snack");
  assert.ok(closeAt > 0 && tabAt > closeAt && snackAt > tabAt);
  const shut = bind.slice(closeAt, tabAt);
  const reopen = bind.slice(tabAt, snackAt);
  assert.match(shut, /state\.snacksOpen = false/);
  assert.match(shut, /return;/);
  assert.doesNotMatch(shut, /spend\(/);
  assert.match(reopen, /state\.snacksOpen = true/);
  assert.match(reopen, /return;/);
  assert.doesNotMatch(reopen, /spend\(/);
  assert.match(client, /Close snacks puts that list away/);
  assert.match(client, /Snacks brings it back/);
  assert.match(css, /#show-snacks-tab\[hidden\]/);
  assert.match(css, /#show-snacks-tab,\s*#show-snacks-close \{[^}]*width: auto/);
  const phoneAt = css.indexOf("@media (max-width: 980px)");
  assert.match(css.slice(phoneAt), /\.phone-fit #show-snacks-tab/);
  assert.match(css.slice(phoneAt), /\.phone-fit \.show-snacks \{[^}]*max-height: 9\.5rem/);
});

test("exit to the square is on the shop card", () => {
  const css = readFileSync(new URL("../1984.css", import.meta.url), "utf8");
  assert.match(html, /id="show-exit">Exit to the square<\/button>/);
  assert.match(client, /id="place-exit">Exit to the square<\/button>/);
  assert.match(client, /closest\("#show-exit"\)\) openMode\("world"\)/);
  assert.match(client, /Exit to the square is on the shop, the bank, Hunt Hall, and the cinema/);
  const wire = sliceFn(client, "wirePlaceExit");
  assert.match(wire, /openMode\("world"\)/);
  for (const name of ["paintShop", "paintBank", "paintHunt", "paintRules", "paintBench", "paintGuide", "paintMint", "paintLayer", "paintKachat", "paintVault"]) {
    assert.match(sliceFn(client, name), /placeActs\(/);
    assert.match(sliceFn(client, name), /wirePlaceExit\(\)/);
  }
  const bank = sliceFn(client, "paintBank");
  assert.match(bank, /id="bank-close">Close<\/button>/);
  assert.match(bank, /id="clerk-back"/);
  assert.match(bank, /You pay/);
  assert.match(bank, /You receive/);
  assert.match(bank, /id="dex-go"/);
  assert.match(bank, /id="dex-flip"/);
  assert.match(sliceFn(client, "enterVenue"), /shop === "mint" \|\| shop === "bank"/);
  assert.match(sliceFn(client, "enterVenue"), /openMode\(shop\)/);
  const busy = sliceFn(client, "setSwapBusy");
  assert.match(busy, /button\.id === "place-exit"/);
  assert.match(css, /#place-exit/);
  assert.match(css, /\.stall-acts/);
});

test("the balances stay in a clear bar under the site tabs", () => {
  const css = readFileSync(new URL("../1984.css", import.meta.url), "utf8");
  const rails = readFileSync(new URL("../rails.html", import.meta.url), "utf8");
  const topEnd = html.indexOf("</header>");
  const barAt = html.indexOf('<header class="kw-bar" id="bar"></header>');
  const stageAt = html.indexOf('<main class="kw-stage">');
  assert.ok(topEnd > 0 && barAt > topEnd && stageAt > barAt);
  assert.doesNotMatch(html.slice(stageAt, stageAt + 400), /id="bar"/);
  assert.match(html, /1984\.css\?v=80/);
  assert.match(html, /1984\/client\.mjs\?v=138/);
  const chrome = sliceFn(client, "paintChrome");
  assert.match(chrome, /id="bar-bank" class="bar-bank/);
  assert.match(chrome, />Bank<\/button>/);
  assert.match(chrome, /<span class="bal-k">tKAS:<\/span>/);
  assert.match(chrome, /<span class="bal-k">POC:<\/span>/);
  assert.match(chrome, /<span class="bal-k">KUSDT:<\/span>/);
  assert.match(chrome, /<span class="bal-k">Address:<\/span>/);
  assert.match(chrome, /<span class="bal-k">Domain:<\/span>/);
  assert.match(chrome, /id="bar-domain"/);
  assert.match(chrome, /domain\/address/);
  assert.match(sliceFn(client, "barChangerHtml"), /kaspatest:/);
  assert.match(sliceFn(client, "barChangerHtml"), /Change KNS name/);
  assert.match(chrome, /Minted:/);
  assert.match(chrome, /Hunt:/);
  assert.match(chrome, /state\.mode === "bank"/);
  assert.match(sliceFn(client, "mintedBarText"), /None yet\./);
  assert.match(sliceFn(client, "huntBarText"), /your promise is on the ledger/);
  assert.match(sliceFn(client, "huntBarText"), /None yet\./);
  assert.match(sliceFn(client, "refreshBankHunts"), /\/api\/1984\/hunts\?address=/);
  assert.match(sliceFn(client, "openMode"), /refreshBankHunts\(\)/);
  assert.match(client, /closest\("#bar-bank"\)/);
  assert.match(client, /openMode\("bank"\)/);
  assert.match(client, /The balances stay in a clear bar under the site tabs/);
  assert.match(client, /\["mint", "Mint"\]/);
  const mintCard = sliceFn(client, "paintMint");
  assert.match(mintCard, /class="dex"/);
  assert.match(mintCard, /You mint/);
  assert.match(mintCard, /id="mint-go" class="dex-go"/);
  assert.match(mintCard, /KCC-20 Last Call/);
  assert.match(mintCard, /No covenant is deployed/);
  assert.doesNotMatch(mintCard, /<strong>What\.<\/strong>/);
  assert.doesNotMatch(mintCard, /<strong>How\.<\/strong>/);
  assert.doesNotMatch(mintCard, /<strong>Why\.<\/strong>/);
  assert.match(mintCard, /name="mint-opt"/);
  assert.match(mintCard, /tab\("more", "Mint"\)/);
  assert.match(mintCard, /tab\("send", "Send"\)/);
  assert.match(mintCard, /tab\("new", "New"\)/);
  assert.match(mintCard, /Type 0 in Cap for no cap/);
  assert.match(mintCard, /0 means no cap\. There is no maximum/);
  assert.match(mintCard, /id="mint-book"/);
  assert.match(mintCard, /id="mint-find"/);
  assert.match(mintCard, /Any funded address can mint more/);
  assert.match(mintCard, /data-mint-view="trade"/);
  assert.match(mintCard, /You pay/);
  assert.match(mintCard, /You receive/);
  assert.match(mintCard, /id="mint-copy">Copy address/);
  assert.match(mintCard, /Not a KAS price/);
  assert.match(mintCard, /Not Zealous Swap/);
  assert.match(mintCard, /Not Kaspa.com/);
  assert.match(sliceFn(client, "openMode"), /panel\.classList\.toggle\("mint-board", mode === "mint" \|\| mode === "groceries"\)/);
  const market = sliceFn(client, "paintMarket");
  assert.match(market, /class="dex"/);
  assert.match(market, /id="market-find"/);
  assert.match(market, /id="market-book"/);
  assert.match(market, /data-face/);
  assert.match(market, /It does not email a brand code/);
  assert.match(market, /https:\/\/www\.coinsbee\.com\/en\/buy-gift-cards-with-kaspa\//);
  assert.match(market, /saleButton\(rail, shop\.id, item\.sku/);
  assert.doesNotMatch(market, /gift code is /);
  assert.match(sliceFn(client, "mintRow"), /mint-tile/);
  assert.match(css, /\.kw-panel\.stall-pop\.mint-board \{[\s\S]*?left: 112px/);
  const phoneAt = css.indexOf("@media (max-width: 980px)");
  const phone = css.slice(phoneAt);
  assert.match(phone, /\.phone-fit \.kw-panel\.stall-pop\.mint-board \{[^}]*left: 4\.7rem[^}]*max-height: none/);
  assert.match(phone, /\.phone-fit \.mint-board \.dex-market \{[^}]*grid-template-columns: 1fr/);
  assert.match(html, /id="mint-open-pop"/);
  assert.match(html, /id="mint-done-pop"/);
  const boards = sliceFn(client, "paintMintBoards");
  assert.match(boards, /<h3>Open<\/h3>/);
  assert.match(boards, /Completed/);
  assert.match(sliceFn(client, "mintDetail"), /data-join/);
  assert.match(sliceFn(client, "mintDetail"), /mint-addr/);
  assert.match(css, /#mint-open-pop \{[\s\S]*?max-height: 52%/);
  assert.match(css, /#mint-done-pop \{[\s\S]*?max-height: calc\(100% - 16px\)/);
  assert.match(css, /\.mint-open, \.layer-scroll, \.chat-scroll, \.vault-scroll \{[\s\S]*?overflow-y: auto/);
  assert.match(html, /id="layer-pop"/);
  assert.match(client, /\["layer", "Layer"\]/);
  const layerCard = sliceFn(client, "paintLayer");
  assert.match(layerCard, /KNS testnet index/);
  assert.match(layerCard, /This square's index/);
  assert.match(layerCard, /network record/);
  assert.match(layerCard, /Visitors can open a published page/);
  assert.match(layerCard, /id="layer-open"/);
  assert.doesNotMatch(layerCard, /id="layer-publish"/);
  const layerPop = sliceFn(client, "paintLayerPop");
  assert.match(layerPop, /id="layer-publish"/);
  assert.match(layerPop, /id="layer-tagline"/);
  assert.match(layerPop, /id="layer-welcome"/);
  assert.match(layerPop, /id="layer-accent"/);
  assert.match(sliceFn(client, "layerVisitHtml"), /You are visiting/);
  assert.match(sliceFn(client, "layerVisitHtml"), /id="layer-inscribe"/);
  assert.match(sliceFn(client, "layerVisitHtml"), /No covenant is deployed/);
  assert.match(sliceFn(client, "layerMakeHtml"), /id="layer-funded"/);
  assert.match(sliceFn(client, "layerMakeHtml"), /id="layer-make"/);
  assert.match(sliceFn(client, "layerMakeHtml"), /id="layer-picked"/);
  assert.match(sliceFn(client, "layerMakeHtml"), /placeholder="name"/);
  assert.match(sliceFn(client, "layerMakeHtml"), /This page adds \.kas/);
  assert.match(css, /\.layer-picked \{[\s\S]*color: #ff4d4d/);
  assert.match(sliceFn(client, "layerSealHtml"), /id="layer-seal"/);
  assert.match(sliceFn(client, "layerSealHtml"), /988 bytes/);
  assert.match(sliceFn(client, "layerSealHtml"), /No covenant is deployed/);
  assert.match(sliceFn(client, "paintLayerPop"), /id="layer-show-name"/);
  assert.match(sliceFn(client, "paintLayerPop"), /Show this name instead of the tKAS address/);
  assert.match(css, /#layer-pop \{[\s\S]*?z-index: 7/);
  assert.match(client, /\["kachat", "Kachat"\]/);
  assert.match(client, /\["vault", "Vault"\]/);
  const vaultCard = sliceFn(client, "paintVault");
  assert.match(vaultCard, /No covenant is deployed/);
  assert.match(vaultCard, /do not belong here/);
  assert.match(vaultCard, /id="vault-save"/);
  assert.match(vaultCard, /value="covenant"/);
  assert.match(vaultCard, /value="nda"/);
  assert.match(sliceFn(client, "paintGuide"), /Vault is on the side rail/);
  assert.match(client, /Layer-Kaspa/);
  assert.match(rails, /<h2>The stag<\/h2>/);
  assert.match(rails, /Layer-Kaspa/);
  assert.match(rails, /kachat\.app\/home/);
  assert.match(css, /\.kw-bar \{[\s\S]*?background: transparent/);
  assert.doesNotMatch(css, /\.kw-bar \{[^}]*right: 8px/);
  assert.doesNotMatch(css, /\.kw-bar \{[^}]*display:\s*none/);
  assert.doesNotMatch(css, /\.kw\.flight \.kw-bar \{ display: none/);
  assert.doesNotMatch(css, /\.kw\.watching \.kw-bar \{ display: none/);
  assert.doesNotMatch(css, /\.kw\.room \.kw-bar \{ display: none/);
});

test("closing the pay slip leaves new purchase on that card", () => {
  const close = sliceFn(client, "closePaySlip");
  assert.match(close, /box\.hidden = true/);
  assert.doesNotMatch(close, /newPurchase|openMode|payPlace/);
  const again = sliceFn(client, "newPurchase");
  assert.match(again, /openMode\(payPlace\)/);
  assert.match(client, /pay-slip-close"\)/);
  assert.match(client, /addEventListener\("click", closePaySlip\)/);
  assert.match(client, /addEventListener\("click", newPurchase\)/);
  assert.match(client, /Close puts that ask away/);
  assert.match(client, /start a new purchase on the card that stays open/);
});

test("the lot sells the roadster and launch shows once it is yours", () => {
  const view = readFileSync(new URL("./view3d.mjs", import.meta.url), "utf8");
  const css = readFileSync(new URL("../1984.css", import.meta.url), "utf8");
  assert.match(html, /id="lot-buy" class="kw-lot-buy"/);
  assert.match(html, />Buy a roadster\. See what happens\.<\/button>/);
  assert.match(html, /id="launch" class="kw-launch"/);
  assert.match(client, /lotBuy\.addEventListener\("click", buyRoadster\)/);
  assert.match(sliceFn(client, "buyRoadster"), /showRoadsterChoice\(\)/);
  assert.match(sliceFn(client, "showRoadsterChoice"), /roadsterBalanceLine\(\)/);
  assert.match(sliceFn(client, "showRoadsterChoice"), /Buy it with POCencept, KUSDT, or tKAS/);
  assert.match(sliceFn(client, "showRoadsterChoice"), /To convert tKAS, POCencept, or KUSDT, go to the bank/);
  assert.match(sliceFn(client, "buyRoadsterOn"), /spend\(rail, "roadster", "keys"\)/);
  assert.match(sliceFn(client, "buyRoadsterOn"), /walkInto\("bank"\)/);
  assert.match(html, /id="need-swap-poc"/);
  assert.match(html, /id="need-swap-kusdt"/);
  assert.match(html, /id="need-swap-kas"/);
  assert.match(html, />Buy with POCencept</);
  assert.match(html, />Buy with KUSDT</);
  assert.match(html, />Buy with tKAS</);
  assert.match(client, /\["need-swap-poc", "poc"\], \["need-swap-kusdt", "kusdt"\], \["need-swap-kas", "kas"\]/);
  assert.match(sliceFn(client, "maybeSwapNotice"), /Pay with a swap/);
  const bought = sliceFn(client, "tookPayment");
  assert.match(bought, /state\.aboard = true/);
  assert.match(bought, /Launch into space is the gold button/);
  assert.match(sliceFn(client, "syncRide"), /showLot = !owns && outside && !gateIsOpen\(\)/);
  assert.match(view, /name = "lot-buy-sign"/);
  assert.match(view, /Buy a roadster\. See what happens\./);
  assert.match(view, /getObjectByName\("lot-buy-sign"\)/);
  assert.match(css, /@keyframes lot-pulse/);
  assert.match(css, /\.kw \.kw-launch \{[\s\S]*animation: lot-pulse/);
  const arm = sliceFn(client, "armMedia");
  assert.match(arm, /el\.muted = false/);
  assert.doesNotMatch(arm, /muted = true/);
  assert.match(arm, /webkit-playsinline/);
  assert.match(arm, /opacity:1/);
  assert.match(arm, /translateX\(-120vw\)/);
  const playFilm = sliceFn(client, "playFlightFilm");
  assert.match(playFilm, /opacity:1/);
  assert.doesNotMatch(playFilm, /opacity:0/);
  assert.match(playFilm, /translateX\(-120vw\)/);
  const left = sliceFn(client, "startLeftFilm");
  assert.match(left, /cuePad\(slots\[0\], PAD_LEFT\)/);
  assert.match(left, /cuePad\(slots\[1\], PAD_RIGHT\)/);
  assert.match(left, /armMedia\(slots\[1\]\)/);
  assert.match(left, /slots\[0\]\.muted = false/);
  assert.match(view, /webkit-playsinline/);
  assert.match(view, /film\.src = side < 0 \? PAD_LEFT : PAD_RIGHT/);
  assert.match(css, /\.flight-film \{[\s\S]*opacity: 1;/);
});
